// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZQeE6cXWBntVnaJVbx09gCEP8KMeXFAA',
    appId: '1:820731255927:web:aac2be9cb53f8a60a2fa72',
    messagingSenderId: '820731255927',
    projectId: 'dalel-el-salehiya',
    authDomain: 'dalel-el-salehiya.firebaseapp.com',
    storageBucket: 'dalel-el-salehiya.firebasestorage.app',
    measurementId: 'G-5G44NHHY6M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu6KsqOOB6yOPC3s4lofq94kT_rJDEVb8',
    appId: '1:820731255927:android:57079b86cedd2661a2fa72',
    messagingSenderId: '820731255927',
    projectId: 'dalel-el-salehiya',
    storageBucket: 'dalel-el-salehiya.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCX_357nR8yxyf4NYMpEPmGn4gMjN05H0',
    appId: '1:820731255927:ios:e223a85106db8ef7a2fa72',
    messagingSenderId: '820731255927',
    projectId: 'dalel-el-salehiya',
    storageBucket: 'dalel-el-salehiya.firebasestorage.app',
    iosBundleId: 'com.dalel.salehiya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCX_357nR8yxyf4NYMpEPmGn4gMjN05H0',
    appId: '1:820731255927:ios:1558ce16d48f36aca2fa72',
    messagingSenderId: '820731255927',
    projectId: 'dalel-el-salehiya',
    storageBucket: 'dalel-el-salehiya.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZQeE6cXWBntVnaJVbx09gCEP8KMeXFAA',
    appId: '1:820731255927:web:e1da3b3d9840fc29a2fa72',
    messagingSenderId: '820731255927',
    projectId: 'dalel-el-salehiya',
    authDomain: 'dalel-el-salehiya.firebaseapp.com',
    storageBucket: 'dalel-el-salehiya.firebasestorage.app',
    measurementId: 'G-R8V91HB0WR',
  );
}
